// Centralized icon mapping for Vaultsign — uses lucide-react
import {
  LayoutDashboard, FileText, FileSignature, PencilLine, Activity,
  BarChart3, Settings, Users, Search, Bell, Plus, ChevronDown,
  CheckCircle2, Clock, Mail, Eye, XCircle, Send, AlertCircle,
  FileCheck, ShieldCheck, KeyRound, Webhook, Plug, CreditCard,
  Building2, GraduationCap, HeartPulse, Home, Landmark, Scale,
  TrendingUp, Wallet, Users2, Menu, X, ArrowUpRight, ArrowRight,
  MoreHorizontal, Filter, Download, Upload, Copy, Trash2, Edit3,
  Calendar, MapPin, Smartphone, Globe, Lock, Sparkles, Zap,
  ChevronRight, Star, Clock3, FilePlus2, RefreshCw, CircleDot,
  ArrowLeft, Check, ExternalLink, Loader2, Info, ChevronUp,
  type LucideIcon,
} from "lucide-react"

export const Icons: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  documents: FileText,
  sign: FileSignature,
  editor: PencilLine,
  tracking: Activity,
  analytics: BarChart3,
  settings: Settings,
  team: Users,
  search: Search,
  bell: Bell,
  plus: Plus,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  check: CheckCircle2,
  clock: Clock,
  mail: Mail,
  eye: Eye,
  xCircle: XCircle,
  send: Send,
  alert: AlertCircle,
  fileCheck: FileCheck,
  shield: ShieldCheck,
  key: KeyRound,
  webhook: Webhook,
  plug: Plug,
  card: CreditCard,
  building: Building2,
  graduation: GraduationCap,
  heart: HeartPulse,
  home: Home,
  landmark: Landmark,
  scale: Scale,
  trending: TrendingUp,
  wallet: Wallet,
  users: Users2,
  menu: Menu,
  x: X,
  arrowUpRight: ArrowUpRight,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  more: MoreHorizontal,
  filter: Filter,
  download: Download,
  upload: Upload,
  copy: Copy,
  trash: Trash2,
  edit: Edit3,
  calendar: Calendar,
  mapPin: MapPin,
  smartphone: Smartphone,
  globe: Globe,
  lock: Lock,
  sparkles: Sparkles,
  zap: Zap,
  star: Star,
  clock3: Clock3,
  filePlus: FilePlus2,
  refresh: RefreshCw,
  dot: CircleDot,
  check2: Check,
  external: ExternalLink,
  loader: Loader2,
  info: Info,
}
